services:
  database:
    image: postgres:16
    container_name: "backend-db"
    restart: unless-stopped
    stop_grace_period: 10s
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: UW8hYdL72BdJGET
      POSTGRES_INITDB_ARGS: "--data-checksums"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: "10s"
      timeout: "5s"
      retries: 5

  # see: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  # see: https://www.pgadmin.org/docs/pgadmin4/latest/import_export_servers.html#json-format
  database-management:
    image: dpage/pgadmin4:latest
    container_name: "backend-db-management"
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - "5050:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
      - "./configs/pgadmin4.servers.json:/pgadmin4/servers.json"
      - "./configs/pgadmin4.preferences.json:/pgadmin4/preferences.json"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@backend.server
      PGADMIN_DEFAULT_PASSWORD: admin@backend.server
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGADMIN_PREFERENCES_JSON_FILE: /pgadmin4/preferences.json
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOGIN_BANNER: '"Use login and password from Docker Compose file"'
    depends_on:
      - database

volumes:
  pgdata:
  pgadmin:
